# Page Static Contact
store_backend_statics_contact:
  path: /contact # chemin vers l'URI
  defaults: { _controller: StoreBackendBundle:Statics:contact }
  # NomduBundle:NomduController:Nomdel'Action

store_backend_statics_about:
  path: /about # chemin vers l'URI
  defaults: { _controller: StoreBackendBundle:Statics:about }
  # NomduBundle:NomduController:Nomdel'Action

store_backend_statics_terms: # ou mentions_legales
  path: /terms # chemin vers l'URI # ou mentions-legales
  defaults: { _controller: StoreBackendBundle:Statics:terms }
  # NomduBundle:NomduController:Nomdel'Action

store_backend_statics_concept:
  path: /concept # chemin vers l'URI
  defaults: { _controller: StoreBackendBundle:Statics:concept }
  # NomduBundle:NomduController:Nomdel'Action