store_backend:
    resource: "@StoreBackendBundle/Resources/config/routing.yml"
    prefix:   /administration

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation


###
# Inscription en Frontend
###

#Subscribe Jeweler Backend
store_backend_security_subscribe:
  path: /subscribe
  defaults: { _controller: StoreBackendBundle:Security:subscribe }

###
# Authentification par Backend et Frontend
###

#Login Backend
store_backend_security_login:
  path: /login
  defaults: { _controller: StoreBackendBundle:Security:login }

#Login Backend Check Action de mon formulaire
store_backend_security_login_check:
  path: /administration/login_check
  defaults: { _controller: StoreBackendBundle:Security:login }


#Logout Backend
store_backend_security_logout:
  path: /administration/logout
