# Page Category list
store_backend_category_list:
  path: /list # chemin vers l'URI
  defaults: { _controller: StoreBackendBundle:Category:list }
  # NomduBundle:NomduController:Nomdel'Action

# Page Category view
store_backend_category_view:
  path: /view/{id}/{name} # chemin vers l'URI
  defaults: { _controller: StoreBackendBundle:Category:view }
  requirements:
    id: \d+
    name: "[a-zA-Z0-9-]{3,30}"
    _method: GET
