# Page CMS list
store_backend_cms_list:
  path: /list # chemin vers l'URI
  defaults: { _controller: StoreBackendBundle:CMS:list }
  # NomduBundle:NomduController:Nomdel'Action

# Page CMS view
store_backend_cms_view:
  path: /view/{id}/{name} # chemin vers l'URI
  defaults: { _controller: StoreBackendBundle:CMS:view }
  requirements:
    id: \d+
    name: "[a-zA-Z0-9-]{3,30}"
    _method: GET
