# Page Products list
store_backend_product_list:
  path: /list # chemin vers l'URI
  defaults: { _controller: StoreBackendBundle:Product:list }
  # NomduBundle:NomduController:Nomdel'Action

# Page View a Product
store_backend_product_view:
  path: /view/{id}/{slug} # chemin vers l'URI
  defaults: { _controller: StoreBackendBundle:Product:view }
  requirements:
    id : \d+
    _method: GET

# remove a Product
store_backend_product_remove:
  path: /remove/{id}
  defaults: { _controller: StoreBackendBundle:Product:remove }

# Page edit a product
store_backend_product_edit:
  path: /edit/{id}
  defaults: { _controller: StoreBackendBundle:Product:edit }

# Page new a product
store_backend_product_new:
  path: /new
  defaults: { _controller: StoreBackendBundle:Product:new }

# Activate a product
store_backend_product_activate:
  path: /activate/{id}/{action}
  defaults: { _controller: StoreBackendBundle:Product:activate }

# Cover a product
store_backend_product_cover:
  path: /cover/{id}/{action}
  defaults: { _controller: StoreBackendBundle:Product:cover }