# Page Products list
store_backend_product_list:
  path: /list # chemin vers l'URI
  defaults: { _controller: StoreBackendBundle:Product:list }
  # NomduBundle:NomduController:Nomdel'Action

# Page View a Product
store_backend_product_view:
  path: /view/{id}/{name} # chemin vers l'URI
  defaults: { _controller: StoreBackendBundle:Product:view }
  requirements:
    id : \d+
    name: "[a-zA-Z0-9-]{5,30}"
    _method: GET