store_backend_supplier_list:
  path: /list
  defaults: { _controller: StoreBackendBundle:Supplier:list }

store_backend_supplier_view:
    path: /view/{id}/{title}
    defaults: { _controller: StoreBackendBundle:Supplier:view }
    requirements:
      id: \d+
      _method: GET

# remove a supplier
store_backend_supplier_remove:
  path: /remove/{id}
  defaults: { _controller: StoreBackendBundle:Supplier:remove }